<a href="https://colab.research.google.com/github/shek-malik-basha/Data-Analytics/blob/main/Numpy_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]

In [2]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]

In [6]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [7]:
len(b)

3

In [9]:
b.ndim

2

In [10]:
b.shape

(3, 3)

In [11]:
c=np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]

In [12]:
c[0,4]=40
print(c)

[[ 1  2  3  4 40  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]

In [13]:
a.dtype

dtype('int64')

In [14]:
np.random.rand(5,5)

array([[0.38173122, 0.61132472, 0.9995011 , 0.9054716 , 0.591222  ],
       [0.12596689, 0.01445184, 0.14162031, 0.14116918, 0.2265027 ],
       [0.88538666, 0.08484725, 0.75805072, 0.37139957, 0.62126092],
       [0.1241399 , 0.76550671, 0.25753594, 0.115351  , 0.54173586],
       [0.38122116, 0.15371478, 0.91604061, 0.97386167, 0.82122047]])

In [15]:
np.random.randint(-1,0,size=(2,2))

array([[-1, -1],
       [-1, -1]])

In [20]:
a = np.arange(12)
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [26]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

In [27]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
import numpy as np

arr = np.zeros((5,5), dtype=int)

arr[2,:] = 1
arr[:,2] = 1

print(arr)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]

In [36]:
f = np.mean(a)
print(f)

5.5

In [37]:
g = np.median(a)
print(g)

5.5

In [38]:
h = np.min(a)
print(h)

0

In [40]:
g = np.max(a)
print(g)

11

In [42]:
i = np.sum(a)
print(i)

66

In [46]:
import pandas as pd
df = pd.read_csv("Walmart_Sales.csv")
df.head(5)

,wwhy n-1 ad wht,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,marks,u,12.2,marks-u,mod marks-u,Unnamed: 19
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106,NaN,NaN,NaN,NaN,NaN,NaN,10.0,14.0,NaN,-4.0,1.0,-1.8
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106,NaN,NaN,NaN,NaN,NaN,NaN,5.0,14.0,NaN,-9.0,NaN,NaN
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106,NaN,NaN,NaN,NaN,NaN,NaN,17.0,14.0,NaN,3.0,NaN,NaN
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106,NaN,NaN,NaN,NaN,NaN,NaN,9.0,14.0,NaN,-5.0,NaN,NaN
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106,NaN,NaN,NaN,NaN,NaN,NaN,20.0,14.0,NaN,6.0,NaN,NaN

In [47]:
df.tail(5)

,wwhy n-1 ad wht,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,marks,u,12.2,marks-u,mod marks-u,Unnamed: 19
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
df.sample(5)

,wwhy n-1 ad wht,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,marks,u,12.2,marks-u,mod marks-u,Unnamed: 19
6362,45,10-06-2011,814395.17,0,73.88,3.881,185.648692,8.521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3595,26,25-06-2010,976242.09,0,63.78,2.810,132.497600,8.512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4460,32,13-08-2010,1157975.68,0,74.97,2.723,190.261155,9.017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5884,42,02-07-2010,507168.80,0,92.89,2.978,126.139200,9.199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3708,26,24-08-2012,1022704.20,0,62.08,3.874,138.281452,7.405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   wwhy n-1 ad wht           6435 non-null   int64
 1   Date                      6435 non-null   object
 2   Weekly_Sales              6435 non-null   float64
 3   Holiday_Flag              6435 non-null   int64
 4   Temperature               6435 non-null   float64
 5   Fuel_Price                6435 non-null   float64
 6   CPI                       6435 non-null   float64
 7   Unemployment              6435 non-null   float64
 8   Unnamed: 8                0 non-null      float64
 9   Unnamed: 9                0 non-null      float64
 10  Unnamed: 10               0 non-null      float64
 11  Unnamed: 11               9 non-null      object
 12  Unnamed: 12               0 non-null      float64
 13  Unnamed: 13               0 non-null      float64
 14  marks                     6 non-null      float64
 15  u                         5 non-null      float64
 16  12.2                      0 non-null      float64
 17  marks-u                   5 non-null      float64
 18  mod marks-u               1 non-null      float64
 19  Unnamed: 19               1 non-null      float64
dtypes: float64(16), int64(2), object(2)
memory usage: 1005.6+ KB

In [55]:
df.shape

(6435, 20)

In [49]:
df.describe()

,wwhy n-1 ad wht,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 12,Unnamed: 13,marks,u,12.2,marks-u,mod marks-u,Unnamed: 19
count,6435.000000,6.435000e+03,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,0.0,0.0,0.0,0.0,0.0,6.000000,5.0,0.0,5.000000,1.0,1.0
mean,23.000000,1.046965e+06,0.069930,60.663782,3.358607,171.578394,7.999151,NaN,NaN,NaN,NaN,NaN,12.200000,14.0,NaN,-1.800000,1.0,-1.8
std,12.988182,5.643666e+05,0.255049,18.444933,0.459020,39.356712,1.875885,NaN,NaN,NaN,NaN,NaN,5.491812,0.0,NaN,6.140033,NaN,NaN
min,1.000000,2.099862e+05,0.000000,-2.060000,2.472000,126.064000,3.879000,NaN,NaN,NaN,NaN,NaN,5.000000,14.0,NaN,-9.000000,1.0,-1.8
25%,12.000000,5.533501e+05,0.000000,47.460000,2.933000,131.735000,6.891000,NaN,NaN,NaN,NaN,NaN,9.250000,14.0,NaN,-5.000000,1.0,-1.8
50%,23.000000,9.607460e+05,0.000000,62.670000,3.445000,182.616521,7.874000,NaN,NaN,NaN,NaN,NaN,11.100000,14.0,NaN,-4.000000,1.0,-1.8
75%,34.000000,1.420159e+06,0.000000,74.940000,3.735000,212.743293,8.622000,NaN,NaN,NaN,NaN,NaN,15.800000,14.0,NaN,3.000000,1.0,-1.8
max,45.000000,3.818686e+06,1.000000,100.140000,4.468000,227.232807,14.313000,NaN,NaN,NaN,NaN,NaN,20.000000,14.0,NaN,6.000000,1.0,-1.8

In [51]:
df.columns

Index(['wwhy n-1 ad wht         ', 'Date', 'Weekly_Sales', 'Holiday_Flag',
       'Temperature', 'Fuel_Price', 'CPI', 'Unemployment', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'marks', 'u', '12.2', 'marks-u', 'mod marks-u',
       'Unnamed: 19'],
      dtype='object')

In [53]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,6425,6426,6427,6428,6429,6430,6431,6432,6433,6434
wwhy n-1 ad wht,1,1,1,1,1,1,1,1,1,1,...,45,45,45,45,45,45,45,45,45,45
Date,05-02-2010,12-02-2010,19-02-2010,26-02-2010,05-03-2010,12-03-2010,19-03-2010,26-03-2010,02-04-2010,09-04-2010,...,24-08-2012,31-08-2012,07-09-2012,14-09-2012,21-09-2012,28-09-2012,05-10-2012,12-10-2012,19-10-2012,26-10-2012
Weekly_Sales,1643690.9,1641957.44,1611968.17,1409727.59,1554806.68,1439541.59,1472515.79,1404429.92,1594968.28,1545418.53,...,718232.26,734297.87,766512.66,702238.27,723086.2,713173.95,733455.07,734464.36,718125.53,760281.43
Holiday_Flag,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
Temperature,42.31,38.51,39.93,46.63,46.5,57.79,54.58,51.45,62.27,65.86,...,72.62,75.09,75.7,67.87,65.32,64.88,64.89,54.47,56.47,58.85
Fuel_Price,2.572,2.548,2.514,2.561,2.625,2.667,2.72,2.732,2.719,2.77,...,3.834,3.867,3.911,3.948,4.038,3.997,3.985,4.0,3.969,3.882
CPI,211.096358,211.24217,211.289143,211.319643,211.350143,211.380643,211.215635,211.018042,210.82045,210.622857,...,191.344887,191.461281,191.577676,191.69985,191.856704,192.013558,192.170412,192.327265,192.330854,192.308899
Unemployment,8.106,8.106,8.106,8.106,8.106,8.106,8.106,8.106,7.808,7.808,...,8.684,8.684,8.684,8.684,8.684,8.684,8.667,8.667,8.667,8.667
Unnamed: 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
marks,10.0,5.0,17.0,9.0,20.0,NaN,12.2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
u,14.0,14.0,14.0,14.0,14.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
marks-u,-4.0,-9.0,3.0,-5.0,6.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mod marks-u,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 19,-1.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
df.isnull().sum()

wwhy n-1 ad wht                0
Date                           0
Weekly_Sales                   0
Holiday_Flag                   0
Temperature                    0
Fuel_Price                     0
CPI                            0
Unemployment                   0
Unnamed: 8                  6435
Unnamed: 9                  6435
Unnamed: 10                 6435
Unnamed: 11                 6426
Unnamed: 12                 6435
Unnamed: 13                 6435
marks                       6429
u                           6430
12.2                        6435
marks-u                     6430
mod marks-u                 6434
Unnamed: 19                 6434
dtype: int64

In [57]:
df.sort_values("Weekly_Sales", ascending=False)

,wwhy n-1 ad wht,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,marks,u,12.2,marks-u,mod marks-u,Unnamed: 19
1905,14,24-12-2010,3818686.45,0,30.59,3.141,182.544590,8.724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2763,20,24-12-2010,3766687.43,0,25.17,3.141,204.637673,7.484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1333,10,24-12-2010,3749057.69,0,57.06,3.236,126.983581,9.003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,4,23-12-2011,3676388.98,0,35.92,3.103,129.984548,5.143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1762,13,24-12-2010,3595903.20,0,34.90,2.846,126.983581,7.795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4671,33,02-12-2011,220060.35,0,59.12,3.701,129.845967,8.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4623,33,31-12-2010,219804.85,1,52.91,3.148,127.087677,9.265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4675,33,30-12-2011,215359.21,1,51.60,3.428,130.071032,8.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4614,33,29-10-2010,213538.32,0,71.34,3.130,126.436419,9.265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4619,33,03-12-2010,209986.25,0,52.82,3.041,126.731333,9.265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df["Weekly_Sales"]

0       1643690.90
1       1641957.44
2       1611968.17
3       1409727.59
4       1554806.68
           ...
6430     713173.95
6431     733455.07
6432     734464.36
6433     718125.53
6434     760281.43
Name: Weekly_Sales, Length: 6435, dtype: float64

In [60]:
df[["Date","Weekly_Sales"]]

            Date  Weekly_Sales
0     05-02-2010    1643690.90
1     12-02-2010    1641957.44
2     19-02-2010    1611968.17
3     26-02-2010    1409727.59
4     05-03-2010    1554806.68
...          ...           ...
6430  28-09-2012     713173.95
6431  05-10-2012     733455.07
6432  12-10-2012     734464.36
6433  19-10-2012     718125.53
6434  26-10-2012     760281.43

[6435 rows x 2 columns]

In [65]:
df[df["Weekly_Sales"] > 1000000]

,wwhy n-1 ad wht,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,marks,u,12.2,marks-u,mod marks-u,Unnamed: 19
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106,NaN,NaN,NaN,NaN,NaN,NaN,10.0,14.0,NaN,-4.0,1.0,-1.8
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106,NaN,NaN,NaN,NaN,NaN,NaN,5.0,14.0,NaN,-9.0,NaN,NaN
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106,NaN,NaN,NaN,NaN,NaN,NaN,17.0,14.0,NaN,3.0,NaN,NaN
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106,NaN,NaN,NaN,NaN,NaN,NaN,9.0,14.0,NaN,-5.0,NaN,NaN
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106,NaN,NaN,NaN,NaN,NaN,NaN,20.0,14.0,NaN,6.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6337,45,17-12-2010,1123282.85,0,30.51,3.140,182.517732,8.724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6338,45,24-12-2010,1682862.03,0,30.59,3.141,182.544590,8.724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6386,45,25-11-2011,1170672.94,1,48.71,3.492,188.350400,8.523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6389,45,16-12-2011,1078905.68,0,39.93,3.413,188.797935,8.523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6390,45,23-12-2011,1521957.99,0,42.27,3.389,188.929975,8.523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
df.sort_values("Weekly_Sales", ascending=True)

,wwhy n-1 ad wht,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,marks,u,12.2,marks-u,mod marks-u,Unnamed: 19
4619,33,03-12-2010,209986.25,0,52.82,3.041,126.731333,9.265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4614,33,29-10-2010,213538.32,0,71.34,3.130,126.436419,9.265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4675,33,30-12-2011,215359.21,1,51.60,3.428,130.071032,8.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4623,33,31-12-2010,219804.85,1,52.91,3.148,127.087677,9.265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4671,33,02-12-2011,220060.35,0,59.12,3.701,129.845967,8.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1762,13,24-12-2010,3595903.20,0,34.90,2.846,126.983581,7.795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,4,23-12-2011,3676388.98,0,35.92,3.103,129.984548,5.143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1333,10,24-12-2010,3749057.69,0,57.06,3.236,126.983581,9.003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2763,20,24-12-2010,3766687.43,0,25.17,3.141,204.637673,7.484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1905,14,24-12-2010,3818686.45,0,30.59,3.141,182.544590,8.724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN